import type { Parcel } from "@/types/parcel";

export const mockParcels: Parcel[] = [
  {
    id: "tv-cedar-creek-01",
    provider: "mock",
    title: "Cedar Creek Mini Ranch",
    address: "148 Mesquite Bend Rd",
    city: "Cedar Creek",
    county: "Bastrop",
    state: "TX",
    price: 84000,
    acreage: 0.72,
    lat: 30.0874,
    lng: -97.5005,
    previewImageUrl:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "paved",
      label: "Paved county road",
    },
    zoningRisk: "low",
    permitFriendliness: "friendly",
    zoningSummary: "County residential, tiny home on foundation allowed with septic plan.",
    terrain: "Level pasture with light tree cover",
    parcelUse: "Residential land",
    nearbyAmenities: ["Bastrop groceries", "County permit office", "Hardware store"],
    estimatedSiteWork: ["Refresh driveway apron", "Confirm septic transfer", "Pad grading"],
    daysOnMarket: 18,
    highlights: ["Existing meter pole", "Septic perc on file", "No HOA"],
    constraints: ["Driveway apron needs refresh"],
  },
  {
    id: "tv-lockhart-02",
    provider: "mock",
    title: "Lockhart Corner Parcel",
    address: "36 Prairie Lark Ln",
    city: "Lockhart",
    county: "Caldwell",
    state: "TX",
    price: 52000,
    acreage: 0.22,
    lat: 29.8849,
    lng: -97.6692,
    previewImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: false },
    roadAccess: {
      available: true,
      type: "gravel",
      label: "Gravel lane",
    },
    zoningRisk: "medium",
    permitFriendliness: "conditional",
    zoningSummary: "Rural residential zoning; septic feasibility still needs county review.",
    terrain: "Open corner lot with shallow slope",
    parcelUse: "Residential land",
    nearbyAmenities: ["Lockhart square", "Fuel and groceries", "Regional builders"],
    estimatedSiteWork: ["Septic feasibility", "Shared lane review", "Utility trench estimate"],
    daysOnMarket: 41,
    highlights: ["Low entry price", "Survey stakes visible", "Flexible setbacks"],
    constraints: ["Septic quote required", "Shared lane maintenance"],
  },
  {
    id: "tv-san-marcos-03",
    provider: "mock",
    title: "San Marcos Infill Lot",
    address: "912 Windmill Hollow",
    city: "San Marcos",
    county: "Hays",
    state: "TX",
    price: 96000,
    acreage: 0.19,
    lat: 29.8833,
    lng: -97.9414,
    previewImageUrl:
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "paved",
      label: "City street frontage",
    },
    zoningRisk: "low",
    permitFriendliness: "friendly",
    zoningSummary: "Small residential build allowed with standard city permits.",
    terrain: "Flat infill lot near utilities",
    parcelUse: "Residential infill",
    nearbyAmenities: ["Downtown San Marcos", "Transit stop", "City utilities office"],
    estimatedSiteWork: ["City permit packet", "Foundation layout", "Setback survey"],
    daysOnMarket: 9,
    highlights: ["City water", "City sewer", "Walkable services"],
    constraints: ["Tighter side setbacks", "Design review likely"],
  },
  {
    id: "tv-wimberley-04",
    provider: "mock",
    title: "Wimberley Oak Pocket",
    address: "207 Live Oak Loop",
    city: "Wimberley",
    county: "Hays",
    state: "TX",
    price: 68000,
    acreage: 0.28,
    lat: 30.0294,
    lng: -98.1182,
    previewImageUrl:
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: false, electricity: true, sewerSeptic: false },
    roadAccess: {
      available: true,
      type: "easement",
      label: "Recorded access easement",
    },
    zoningRisk: "medium",
    permitFriendliness: "conditional",
    zoningSummary: "ETJ parcel with well and septic due diligence needed.",
    terrain: "Oak canopy with buildable clearing",
    parcelUse: "Rural residential",
    nearbyAmenities: ["Wimberley town center", "Well contractor", "Septic installer"],
    estimatedSiteWork: ["Well budget", "Easement review", "Tree-safe pad placement"],
    daysOnMarket: 63,
    highlights: ["Private setting", "Electric nearby", "Good pad option"],
    constraints: ["Well required", "Easement review"],
  },
  {
    id: "tv-dripping-springs-05",
    provider: "mock",
    title: "Dripping Springs Eco Tract",
    address: "64 Juniper Ridge Pass",
    city: "Dripping Springs",
    county: "Hays",
    state: "TX",
    price: 145000,
    acreage: 0.42,
    lat: 30.1902,
    lng: -98.0867,
    previewImageUrl:
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: false },
    roadAccess: {
      available: true,
      type: "paved",
      label: "Private paved road",
    },
    zoningRisk: "high",
    permitFriendliness: "challenging",
    zoningSummary: "Hill Country design controls and septic approvals add schedule risk.",
    terrain: "Rocky ridge with long views",
    parcelUse: "Rural residential",
    nearbyAmenities: ["Dripping Springs services", "Design review consultants", "Trail access"],
    estimatedSiteWork: ["Septic engineering", "Rock trenching", "Drive approach planning"],
    daysOnMarket: 24,
    highlights: ["Premium views", "Water tap available", "Strong resale area"],
    constraints: ["Higher permit friction", "Septic engineering likely"],
  },
  {
    id: "tv-elgin-06",
    provider: "mock",
    title: "Elgin Pasture Starter",
    address: "511 County Line Spur",
    city: "Elgin",
    county: "Bastrop",
    state: "TX",
    price: 61000,
    acreage: 0.55,
    lat: 30.3497,
    lng: -97.3703,
    previewImageUrl:
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: false, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "gravel",
      label: "Gravel county frontage",
    },
    zoningRisk: "low",
    permitFriendliness: "friendly",
    zoningSummary: "County jurisdiction with favorable tiny home precedent nearby.",
    terrain: "Cleared pasture with mild drainage",
    parcelUse: "Unrestricted residential",
    nearbyAmenities: ["Elgin town center", "Feed and hardware", "County road access"],
    estimatedSiteWork: ["Water source quote", "Culvert install", "Drainage check"],
    daysOnMarket: 36,
    highlights: ["Room for garden", "Septic feasible", "Low restrictions"],
    constraints: ["Water haul or well", "Culvert needed"],
  },
  {
    id: "tv-taylor-07",
    provider: "mock",
    title: "Taylor Utility-Ready Lot",
    address: "83 Cottonwood Row",
    city: "Taylor",
    county: "Williamson",
    state: "TX",
    price: 74000,
    acreage: 0.31,
    lat: 30.5708,
    lng: -97.4095,
    previewImageUrl:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "paved",
      label: "Paved neighborhood street",
    },
    zoningRisk: "low",
    permitFriendliness: "friendly",
    zoningSummary: "Residential lot with utility taps and compact-home precedent.",
    terrain: "Open lot with mature edge trees",
    parcelUse: "Residential land",
    nearbyAmenities: ["Taylor town center", "Utility service desk", "Regional job centers"],
    estimatedSiteWork: ["Tap verification", "Pad staking", "Driveway permit"],
    daysOnMarket: 14,
    highlights: ["Utility taps", "Fast permit path", "Rail town services"],
    constraints: ["Small storage setback"],
  },
  {
    id: "tv-georgetown-08",
    provider: "mock",
    title: "Georgetown Pocket Acreage",
    address: "119 Whitecap Crossing",
    city: "Georgetown",
    county: "Williamson",
    state: "TX",
    price: 130000,
    acreage: 0.84,
    lat: 30.6333,
    lng: -97.6779,
    previewImageUrl:
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "paved",
      label: "County road frontage",
    },
    zoningRisk: "low",
    permitFriendliness: "friendly",
    zoningSummary: "Residential acreage outside strict subdivision controls.",
    terrain: "Wide lot with rear tree line",
    parcelUse: "Residential acreage",
    nearbyAmenities: ["Georgetown services", "Medical center", "Building supply"],
    estimatedSiteWork: ["Longer utility run", "Drive pad", "Survey refresh"],
    daysOnMarket: 28,
    highlights: ["Large build envelope", "Utility-ready", "Low flood risk"],
    constraints: ["Higher acquisition cost"],
  },
  {
    id: "tv-lago-vista-09",
    provider: "mock",
    title: "Lago Vista Hillside Lot",
    address: "42 Cactus View Ct",
    city: "Lago Vista",
    county: "Travis",
    state: "TX",
    price: 89000,
    acreage: 0.16,
    lat: 30.4602,
    lng: -97.9883,
    previewImageUrl:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: true, electricity: true, sewerSeptic: false },
    roadAccess: {
      available: true,
      type: "easement",
      label: "Steep private drive",
    },
    zoningRisk: "high",
    permitFriendliness: "challenging",
    zoningSummary: "Slope, access, and septic constraints require extra engineering.",
    terrain: "Compact hillside lot",
    parcelUse: "Residential hillside",
    nearbyAmenities: ["Lake access", "Lago Vista services", "Hill Country contractors"],
    estimatedSiteWork: ["Slope engineering", "Access grading", "Septic feasibility"],
    daysOnMarket: 87,
    highlights: ["Lake-area demand", "Water available", "Quiet cul-de-sac"],
    constraints: ["Slope engineering", "Small build envelope", "Septic uncertain"],
  },
  {
    id: "tv-marble-falls-10",
    provider: "mock",
    title: "Marble Falls Ridge Lot",
    address: "705 Bluebonnet Ridge",
    city: "Marble Falls",
    county: "Burnet",
    state: "TX",
    price: 118000,
    acreage: 1.15,
    lat: 30.5782,
    lng: -98.2728,
    previewImageUrl:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=700&q=80",
    priceSource: "listing",
    utilities: { water: false, electricity: true, sewerSeptic: true },
    roadAccess: {
      available: true,
      type: "gravel",
      label: "Gravel ranch road",
    },
    zoningRisk: "medium",
    permitFriendliness: "conditional",
    zoningSummary: "Rural parcel with room for a tiny home, but water source must be solved.",
    terrain: "Hilltop acreage with caliche drive",
    parcelUse: "Rural residential acreage",
    nearbyAmenities: ["Marble Falls services", "Well contractors", "Lake-area trades"],
    estimatedSiteWork: ["Water source plan", "Longer drive prep", "Pad compaction"],
    daysOnMarket: 52,
    highlights: ["Excellent privacy", "Large usable pad", "Electric at road"],
    constraints: ["Well or water haul", "Longer commute"],
  },
];
